---
name: actionpack
version: '6.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 3670834268f4ea9c10aefeffae7e072b51256375
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
